[package]
name = "fey_lua"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "Temp types and helpers for Lua integration."

[dependencies]
fnv = "1.0.7"
mlua = { version = "0.11.5", features = ["lua54", "vendored"] }
