[package]
name = "fey_packer"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "A 2D rectangle packer."

[dependencies]
fey_math = { version = "0.1.0", path = "../fey_math" }
