[package]
name = "texture_packer"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "Texture packer example."

[dependencies]
polywog = { version = "0.1.0", path = "../../polywog" }
env_logger = "0.11.8"
