[package]
name = "minimal"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "Minimal example."

[dependencies]
kero = { version = "0.2.0", path = "../.." }