[package]
name = "smooth_moves"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "Smooth movement example."

[dependencies]
env_logger = "0.11.8"
polywog = { version = "0.1.0", path = "../../polywog" }
