[package]
name = "minimal_lua"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "Minimal Lua example."

[dependencies]
env_logger = "0.11.8"
polywog = { version = "0.1.0", path = "../../polywog", features = ["lua"] }
