[package]
name = "controller"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
description = "Controller example."

[dependencies]
kero = { version = "0.1.0", path = "../.." }
